# conda env create --file enviroment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
 - python={{ cookiecutter.python_version }}
  {% if cookiecutter.project_packages == "All" -%}
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - jupyter
  - statsmodels
  - scipy
  - tensorflow  # O usa 'torch' para PyTorch, según el caso
  - xgboost
  - plotly
  - sqlalchemy
  - lightgbm
  - dask
  - mlflow
  {% endif -%}
  - pip
  {% if cookiecutter.project_packages == "All" -%}
  - pyprojroot
  {% endif -%}
  - python={{ cookiecutter.python_version }}
  - pip:
    {% if cookiecutter.project_packages == "All" -%}
    - pyhere
    {% endif -%}